# Read the Docs configuration file
version: 2

# Build documentation in the docs/ directory with Sphinx
sphinx:
  configuration: docs/conf.py
  fail_on_warning: false

# Build with Python 3.8+
build:
  os: ubuntu-22.04
  tools:
    python: "3.11"

# Install dependencies
python:
  install:
    - requirements: docs/requirements.txt

# Optional: build formats
formats: 
  - pdf
  - epub
